version: "3.8"

services:
  local_postgres:
    container_name: "local_postgres"
    image: "postgres:latest"
    restart: "unless-stopped"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_EXPOSE_PORT}:5432  # internal container port
    volumes: 
      - ${VOLUMES_BASE_DIR}/postgresql:/var/lib/postgresql/data

  local_postgres_admin:
    container_name: "local_postgres_admin"
    image: "dpage/pgadmin4:latest"
    restart: "unless-stopped"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_EXPOSE_PORT}:80 # internal container port
    volumes: 
      - ${VOLUMES_BASE_DIR}/pgadmin:/var/lib/pgadmin
    depends_on:
      - local_postgres

  local_mongodb:
    container_name: "local_mongodb"
    image: "mongo:latest"
    restart: "unless-stopped"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - ${MONGO_EXPOSE_PORT}:27017
    volumes:
      - ${VOLUMES_BASE_DIR}/mongodb:/data/db

  local_rabbitmq:
    container_name: "local_rabbitmq"
    image: "rabbitmq:3-management"  #this specific image has the Web UI enabled by default
    restart: "unless-stopped"
    ports:
        - ${RABBITMQ_AMQP_EXPOSE_PORT}:5672
        - ${RABBITMQ_MANAGEMENT_EXPOSE_PORT}:15672
    environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
        - ${VOLUMES_BASE_DIR}/rabbitmq:/var/lib/rabbitmq

  local_grafana:
    container_name: "local_grafana"
    image: "grafana/grafana:latest"
    restart: "unless-stopped"
    ports:
      - ${GRAFANA_EXPOSE_PORT}:3000
    volumes:
      - ${VOLUMES_BASE_DIR}/grafana:/var/lib/grafana

  local_prometheus:
    container_name: "local_prometheus"
    image: "prom/prometheus:latest"
    ports:
      - ${PROMETHEUS_EXPOSE_PORT}:9090
    volumes:
      - ./config/prometheus:/etc/prometheus
      - ${VOLUMES_BASE_DIR}/prometheus:/prometheus

  local_standalone_redis:
    container_name: "local_standalone_redis"
    image: "redis:latest"
    restart: "unless-stopped"
    ports:
      - ${REDIS_EXPOSE_PORT}:6379
    environment:
      - REDIS_REPLICATION_MODE=${REDIS_REPLICATION_MODE}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes: 
      - ${VOLUMES_BASE_DIR}/redis:/data

  local_redis_exporter:
    container_name: "local_redis_exporter"
    image: "oliver006/redis_exporter:latest"
    restart: "unless-stopped"
    ports:
      - ${REDIS_EXPORTER_EXPOSE_PORT}:9121
    environment:
      - REDIS_ADDR=local_standalone_redis:6379
      # - REDIS_USER: null
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    links:
      - local_standalone_redis
      - local_prometheus
    
networks:
  default: 
    name: "development-tools-network"
    attachable: true  # allows other containers/compose projects to connect to this network


# to run the tools, use the following command:
# docker compose --env-file ./env/.env up

# make sure the file ./env/.env is present; use the ./env/.env.template to produce it
